# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://loving-johnson-b4b63a.netlify.com/"
languageCode = "en-EN"
title = "Wize AI"

defaultContentLanguage = "en"

# Metadata
[params]
  author = "Your name"
  description = "Virtual assistant of the future. Today"

# Hero section (from here on is for icon theme)
[languages]
[languages.en]
weight = 0
title  = "Wize AI"

[languages.et]
weight = 1
title = "Wize AI"

[languages.en.hero]
  img = "/images/geometric-bg-overlay-wizeblue.jpg"
  title = ""
  description = ""
  
# Hero section estonian (from here on is for icon theme)
[languages.et.hero]
  img = "/images/geometric-bg-overlay-wizeblue.jpg"
  title = "Virtual assistant of the future. Today"
  description = ""

# Navigation section
[params.nav]
  mission = ""
  services = ""
  team = ""
  contact = "Chat"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "/images/img_3.jpg"
    [[params.mission.images.list]]
      img = "/images/img_2.jpg"
    [[params.mission.images.list]]
      img = "/images/img_1.jpg"
    [[params.mission.images.list]]
      img = "/images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "Lorem ipsumt"
    title = "Lorem ipsum"
    subtitle = "Lorem ipsum dolor sit amet, a suspendisse ipsum quis erat in."
    description = "<p>Lorem ipsum dolor sit amet, potenti vel erat id ante, rhoncus porta proin venenatis et, lorem eget condimentum tellus, morbi massa luctus magnis. Dui et doloremque ac, et amet dictum sodales ac, massa ultrices diam in, luctus nunc condimentum venenatis in. Praesent est imperdiet adipiscing tellus, sociis magnis mauris a, ipsum eros erat malesuada a, amet semper eget in. Vel aliquet quis nibh, nulla nunc id augue.</p><ul class='checked'><li>Lorem ipsum</li><li>Lorem ipsum</li><li>Lorem ipsum</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Value"
    subtitle = "Lorem ipsum dolor sit amet, a suspendisse ipsum quis erat in."
    description = "<p> </p><ul class='checked'><li>Lorem ipsum dolor sit amet, potenti vel erat id ante, rhoncus porta proin venenatis et, lorem eget condimentum tellus, morbi massa luctus magnis. Dui et doloremque ac, et amet dictum sodales ac, massa ultrices diam in, luctus nunc condimentum venenatis in. Praesent est imperdiet adipiscing tellus, sociis magnis mauris a, ipsum eros erat malesuada a, amet semper eget in. Vel aliquet quis nibh, nulla nunc id augue.</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"
 
 [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Mission"
    subtitle = "Lorem ipsum dolor sit amet, a suspendisse ipsum quis erat in."
    description = "<p>Lorem ipsum dolor sit amet, potenti vel erat id ante, rhoncus porta proin venenatis et, lorem eget condimentum tellus, morbi massa luctus magnis. Dui et doloremque ac, et amet dictum sodales ac, massa ultrices diam in, luctus nunc condimentum venenatis in. Praesent est imperdiet adipiscing tellus, sociis magnis mauris a, ipsum eros erat malesuada a, amet semper eget in. Vel aliquet quis nibh, nulla nunc id augue.</p><ul class='checked'><li>Lorem ipsum</li><li>Lorem ipsum</li><li>Lorem ipsum</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = true
  video = true
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Services"
  description = "Lorem ipsum dolor sit amet, a suspendisse ipsum quis erat in."

  [[params.services.item]]
    icon = "icon-speech"
    title = "Lorem ipsum"
    description = "Vitae erat, vitae nec sed facilisis congue tincidunt, eget vel wisi ratione et dui."

  [[params.services.item]]
    icon = "icon-wrench"
    title = "Lorem ipsum"
    description = "Vitae erat, vitae nec sed facilisis congue tincidunt, eget vel wisi ratione et dui."

  [[params.services.item]]
    icon = "icon-magic-wand"
    title = "Lorem ipsum"
    description = "Vitae erat, vitae nec sed facilisis congue tincidunt, eget vel wisi ratione et dui."

  [[params.services.item]]
    icon = "icon-support"
    title = "Lorem ipsum"
    description = "Vitae erat, vitae nec sed facilisis congue tincidunt, eget vel wisi ratione et dui."
    
  [[params.services.item]]
    icon = "icon-pencil"
    title = "Lorem ipsum"
    description = "Vitae erat, vitae nec sed facilisis congue tincidunt, eget vel wisi ratione et dui."

  [[params.services.item]]
    icon = "icon-directions"
    title = "ILorem ipsum"
    description = "Vitae erat, vitae nec sed facilisis congue tincidunt, eget vel wisi ratione et dui."
    
# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Lorem ipsum"
    img = "/images/img_1.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Lorem ipsum"
    img = "/images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "/images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "/images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "/images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "/images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "/images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "/images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = "Lorem ipsum"

  [[params.team.item]]
    name = "Lorem"
    position = "Lorem"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "/images/person4.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"
    linkedin = "#"

  [[params.team.item]]
    name = "Lorem"
    position = "Lorem"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "/images/person4.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "Lorem"
    position = "Lorem"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "/images/person4.jpg"
    facebook = "#"
    twitter = "#"
    dribbble = "#"
    instagram = "#"
    github = "#"

  # [[params.team.item]]
  #   name = "Jason Doe"
  #   position = "Chief haranguer"
  #   description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  #   img = "images/person4.jpg"
  #   facebook = "#"
  #   twitter = "#"
  #   dribbble = "#"
  #   instagram = "#"
  #   github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "#"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"
  
